### ISSUE TITLE
How to create complex BERT encoder-decoder using the models in Ch.9?

### ISSUE THREAD

**Issue by andysingal** [PacktPublishing/The-Regularization-Cookbook#6]
I was looking for something like this: <img width="314" alt="Screenshot 2023-09-06 at 1 31 56 PM" src="https://github.com/PacktPublishing/The-Regularization-Cookbook/assets/20493493/118541a1-5907-46be-adf0-20431af21efd">

How can i code it and what other factors i can use?

**Comment by vincent-vdb** [comment]
Hi @andysingal,

Generally speaking, I would say there are two ways of building a custom architecture:
- Either someone already did it with a permissive enough license and you can reuse it yourself
- Either you do it yourself

I believe you want to do it yourself, in which case you have to build the graph using Pytorch. I didn't check carefully, but it seems all is already implemented in Pytorch, you just have to reuse the implemented classes and functions.

Since this is not related to the book itself or its content but it's more an open question about a specific project of yours, I will close this issue, but feel free to open new issues if needed.
